# Generated by Django 6.1.1 on 2026-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300)),
                ('direccion_matriz', models.CharField(max_length=300)),
                ('direccion_establecimiento', models.CharField(max_length=300)),
                ('codigo_establecimiento', models.CharField(default='001', max_length=3)),
                ('codigo_punto_emision', models.CharField(default='001', max_length=3)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('contribuyente_especial', models.CharField(blank=True, max_length=20)),
                ('ambiente', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1)),
                ('certificado_p12', models.BinaryField(blank=True, null=True)),
                ('certificado_password_cifrada', models.CharField(blank=True, max_length=500)),
                ('secuencial_factura', models.PositiveIntegerField(default=1)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emisor',
                'verbose_name_plural': 'Emisores',
            },
        ),
    ]
