# Generated by Django 6.1.1 on 2026-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emisor',
            options={},
        ),
        migrations.AddField(
            model_name='emisor',
            name='es_rimpe_emprendedor',
            field=models.BooleanField(default=False),
        ),
    ]
