# Generated by Django 6.1.1 on 2026-09-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emisores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencial', models.CharField(max_length=9)),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tipo_identificacion_comprador', models.CharField(default='07', max_length=2)),
                ('identificacion_comprador', models.CharField(default='9999999999999', max_length=20)),
                ('razon_social_comprador', models.CharField(default='CONSUMIDOR FINAL', max_length=300)),
                ('direccion_comprador', models.CharField(blank=True, max_length=300)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payload_original', models.JSONField()),
                ('estado', models.CharField(choices=[('CREADO', 'Creado'), ('FIRMADO', 'Firmado'), ('ENVIADO', 'Enviado al SRI'), ('RECIBIDA', 'Recibida por el SRI'), ('AUTORIZADO', 'Autorizado'), ('NO_AUTORIZADO', 'No autorizado'), ('ERROR', 'Error')], default='CREADO', max_length=20)),
                ('xml_generado', models.TextField(blank=True)),
                ('xml_firmado', models.TextField(blank=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='emisores.emisor')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=12)),
                ('precio_unitario_sin_impuesto', models.DecimalField(decimal_places=6, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_porcentaje_iva', models.CharField(max_length=1)),
                ('tarifa_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_externa__gt', '')), fields=('emisor', 'referencia_externa'), name='unico_por_emisor_y_referencia_externa'),
        ),
    ]
